version: '3.8'

services:
  faceon-admin:
    build: .
    ports:
      - "8501:8501"
    environment:
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
    env_file:
      .env